<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJn5o5xx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJn5o5xx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJn5o5xx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJn5o5xx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJn5o5xx\appProdProjectContainer(array(
    'container.build_hash' => 'Jn5o5xx',
    'container.build_id' => '316ad6be',
    'container.build_time' => 1533824178,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJn5o5xx');
