<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrxfedd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrxfedd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZrxfedd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZrxfedd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZrxfedd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zrxfedd',
    'container.build_id' => '6b1da50f',
    'container.build_time' => 1534234088,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrxfedd');
